[tool.poetry]
name = "webstore"
version = "0.1.0"
description = ""
authors = ["thaokaka <thaotrung1966@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django-unfold = "^0.20.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
