# Generated by Django 4.2.9 on 2024-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
