# Generated by Django 4.2.9 on 2024-01-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('sku', models.TextField(blank=True, max_length=255)),
                ('brand', models.TextField(blank=True, max_length=255)),
                ('material', models.TextField(blank=True, max_length=255)),
                ('size', models.TextField(blank=True, max_length=255)),
                ('function', models.TextField(blank=True, max_length=255)),
                ('warranty', models.TextField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('sold', models.IntegerField(blank=True, null=True)),
                ('power_supply', models.TextField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('price', models.IntegerField(blank=True)),
                ('sale_price', models.IntegerField(blank=True)),
                ('images', models.TextField(blank=True, max_length=2000)),
                ('videos', models.TextField(blank=True, max_length=2000)),
                ('status', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
