# Generated by Django 4.0.6 on 2024-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
